# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rbkb-http}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Monti"]
  s.date = %q{2009-11-12}
  s.description = %q{HTTP libraries and tools based on and complementary to Ruby BlackBag}
  s.email = %q{emonti@matasano.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rbkb/http.rb",
     "lib/rbkb/http/base.rb",
     "lib/rbkb/http/body.rb",
     "lib/rbkb/http/common.rb",
     "lib/rbkb/http/headers.rb",
     "lib/rbkb/http/parameters.rb",
     "lib/rbkb/http/request.rb",
     "lib/rbkb/http/response.rb",
     "rbkb-http.gemspec",
     "spec/rbkb-http_spec.rb",
     "spec/spec_helper.rb",
     "test/test_helper.rb",
     "test/test_http.rb",
     "test/test_http_helper.rb",
     "test/test_http_request.rb",
     "test/test_http_response.rb"
  ]
  s.homepage = %q{http://github.com/emonti/rbkb-http}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{HTTP protocol add-ons for Ruby BlackBag}
  s.test_files = [
    "spec/rbkb-http_spec.rb",
     "spec/spec_helper.rb",
     "test/test_helper.rb",
     "test/test_http.rb",
     "test/test_http_helper.rb",
     "test/test_http_request.rb",
     "test/test_http_response.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<rbkb>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rbkb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rbkb>, [">= 0"])
  end
end
